### ISSUE TITLE
Mejorar question-captcha de Registro 

### ISSUE THREAD

**Issue by torehc** [kreitek/metaespacio#17]
Es necesario cambiar el Captcha ya que falla mucho, sobretodo cuando se hace el registro desde dispositivos móviles...

**Comment by amd77** [comment]
Se ha puesto un capcha simplificado, y quitado el existente. El capcha hace una pregunta y espera una respuesta. Se ha puesto de forma ampliable por si hay alguien que quiera definir más preguntas, mas listas o mas tontas. Y quedaria pendiente que el formulario eligiese una pregunta de esas al azar y la conservase (en la sesión o en el paso del form por ejemplo).

**Comment by amd77** [comment]
Me dice lucas que esto lo hace el siempre en base de datos. Esa podria ser una alternativa, crear un modelo de preguntas y respuestas para poderlas agregar dinamicamente. De cualquier forma, lo que se pretendes es parar el spam y no hacer un trivial pirsuit. Ya lo vemos.

**Comment by enen** [comment]
Si alguien más se queja se revisa. Por lo pronto lo cierro
